parameters:
    acme_csvcleanerconnector.array_converter.flat.product.class: Acme\Bundle\CsvCleanerConnectorBundle\ArrayConverter\ProductStandardConverter

services:
    acme_csvcleanerconnector.array_converter.flat.product:
        class: %acme_csvcleanerconnector.array_converter.flat.product.class%
        arguments:
            - '@pim_connector.array_converter.flat.product'
