language: php
php: 5.6

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

# disable xdebug
before_install:
  - phpenv config-rm xdebug.ini
  - export PATH=$HOME/.local/bin:$PATH
  - mysql -e 'CREATE DATABASE IF NOT EXISTS akeneo_pim;'

# command to install dependencies
install:
 - "pip install --user `whoami` sphinx~=1.5.3 git+https://github.com/fabpot/sphinx-php.git git+https://github.com/mickaelandrieu/sphinxcontrib.youtube.git"

# command to run tests
script:
 - composer install --no-ansi --no-interaction --no-progress
 - sphinx-build -nWT -b linkcheck . _build/
# Flags used here
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
#  -T   Displays the full stack trace if an unhandled exception occurs. 
#  linkcheck builder checks for broken links.
