extensions:
    acme-job-instance-csv-base-import-edit:
        module: pim/form/common/edit-form

    acme-job-instance-csv-base-import-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: acme-job-instance-csv-base-import-edit
        position: 1000

    acme-job-instance-csv-base-import-edit-tabs:
        module: pim/form/common/form-tabs
        parent: acme-job-instance-csv-base-import-edit
        targetZone: content
        position: 100

    acme-job-instance-csv-base-import-edit-properties:
        module: pim/job/common/edit/properties
        parent: acme-job-instance-csv-base-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: acme-job-instance-properties

    acme-job-instance-csv-base-import-edit-history:
        module: pim/common/tab/history
        parent: acme-job-instance-csv-base-import-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: acme-job-instance-history

    acme-job-instance-csv-base-import-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    acme-job-instance-csv-base-import-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    acme-job-instance-csv-base-import-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-edit-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.filePath.help

    acme-job-instance-csv-base-import-show-properties-escape:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.escape
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.escape.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.escape.help

    acme-job-instance-csv-base-import-edit-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: acme-job-instance-csv-base-import-edit-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.uploadAllowed.help

    acme-job-instance-csv-base-import-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-edit-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.delimiter.help

    acme-job-instance-csv-base-import-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-edit-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.enclosure.help

    acme-job-instance-csv-base-import-edit-label:
        module: pim/job/common/edit/label
        parent: acme-job-instance-csv-base-import-edit
        targetZone: title
        position: 100

    acme-job-instance-csv-base-import-edit-meta:
        module: pim/job/common/edit/meta
        parent: acme-job-instance-csv-base-import-edit
        targetZone: meta
        position: 100

    acme-job-instance-csv-base-import-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: acme-job-instance-csv-base-import-edit
        targetZone: back
        aclResourceId: pim_importexport_import_profile_index
        position: 80
        config:
            backUrl: pim_importexport_import_profile_index

    acme-job-instance-csv-base-import-edit-delete:
        module: pim/job/import/edit/delete
        parent: acme-job-instance-csv-base-import-edit
        targetZone: buttons
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    acme-job-instance-csv-base-import-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: acme-job-instance-csv-base-import-edit
        targetZone: buttons
        position: 120

    acme-job-instance-csv-base-import-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: acme-job-instance-csv-base-import-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    acme-job-instance-csv-base-import-edit-state:
        module: pim/form/common/state
        parent: acme-job-instance-csv-base-import-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    acme-job-instance-csv-base-import-edit-validation:
        module: pim/job/common/edit/validation
        parent: acme-job-instance-csv-base-import-edit

    acme-job-instance-csv-base-import-show:
        module: pim/form/common/edit-form

    acme-job-instance-csv-base-import-show-tabs:
        module: pim/form/common/form-tabs
        parent: acme-job-instance-csv-base-import-show
        targetZone: content
        position: 100

    acme-job-instance-csv-base-import-show-upload:
        module: pim/job/common/edit/upload
        parent: acme-job-instance-csv-base-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: content
        position: 90

    acme-job-instance-csv-base-import-show-properties:
        module: pim/job/common/edit/properties
        parent: acme-job-instance-csv-base-import-show-tabs
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: acme-job-instance-properties

    acme-job-instance-csv-base-import-show-history:
        module: pim/common/tab/history
        parent: acme-job-instance-csv-base-import-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: acme-job-instance-history

    acme-job-instance-csv-base-import-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    acme-job-instance-csv-base-import-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    acme-job-instance-csv-base-import-show-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.filePath.help

    acme-job-instance-csv-base-import-show-properties-escape:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.escape
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.escape.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.escape.help

    acme-job-instance-csv-base-import-show-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.delimiter.help

    acme-job-instance-csv-base-import-show-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: acme-job-instance-csv-base-import-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.enclosure.help

    acme-job-instance-csv-base-import-show-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: acme-job-instance-csv-base-import-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.uploadAllowed.help

    acme-job-instance-csv-base-import-show-label:
        module: pim/job/common/edit/label
        parent: acme-job-instance-csv-base-import-show
        targetZone: title
        position: 100

    acme-job-instance-csv-base-import-show-meta:
        module: pim/job/common/edit/meta
        parent: acme-job-instance-csv-base-import-show
        targetZone: meta
        position: 100

    acme-job-instance-csv-base-import-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: acme-job-instance-csv-base-import-show
        targetZone: back
        aclResourceId: pim_importexport_import_profile_index
        position: 80
        config:
            backUrl: pim_importexport_import_profile_index

    acme-job-instance-csv-base-import-show-edit:
        module: pim/common/redirect
        parent: acme-job-instance-csv-base-import-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_import_profile_edit
            identifier:
                path: code
                name: code

    acme-job-instance-csv-base-import-show-launch:
        module: pim/job/common/edit/upload-launch
        parent: acme-job-instance-csv-base-import-show
        aclResourceId: pim_importexport_import_profile_launch
        targetZone: buttons
        position: 110
        config:
            launch: pim_enrich.form.job_instance.button.import.launch
            upload: pim_enrich.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code
