datagrid:
    color:
        extends: custom_entity
        options:
            entityHint: color
        columns:
            code:
                label: Code
            label:
                label: Label
            created:
                label: Created
                frontend_type: date
            updated:
                label: Updated
                frontend_type: date
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: o.code
                label:
                    type:      string
                    label:     Label
                    data_name: translation.label
                created:
                    type:             date
                    label:            Created
                    data_name:        o.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        o.udapted
                    filter_by_having: true
        sorters:
            columns:
                code:
                    data_name: o.code
                label:
                    data_name: translation.label
                created:
                    data_name: o.created
                updated:
                    data_name: o.udapted
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
