services:
    acme_enrich.mass_edit_action.capitalize_values:
        public: false
        class: Acme\Bundle\EnrichBundle\MassEditAction\Operation\CapitalizeValues
        tags:
            -
                name: pim_enrich.mass_edit_action
                alias: capitalize-values
                acl: acme_enrich_product_capitalize_values
                datagrid: product-grid
                operation_group: mass-edit
                form_type: acme_enrich.form.type.capitalize_values
