parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: akeneo_pim
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    websocket_host: 127.0.0.1
    websocket_port: 8080
    session_handler: null
    locale: en_US
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: '2014-02-13T15:05:07+01:00'
    upload_dir: '%kernel.root_dir%/uploads/product'
    archive_dir: '%kernel.root_dir%/archive'
    installer_data: 'AcmeMyBundle:mydataset'
    uservoice_key: VuTQAMdehvLUshGkqiwVyQ
    mass_edit_limit: 1000
