groups:
  Buttons:
    AknButton:
      description: "Prints buttons with text, with or without an icon. You can mix this module's modifiers: for example, you can create a big important uppercase button with an icon. If the button contains only an icon, please use the AknIconButton module."
      modifiers:
        Big button: { class: 'AknButton--big' }
        Small button: { class: 'AknButton--small' }
        Micro button: { class: 'AknButton--micro' }
        Apply button: { class: 'AknButton--apply' }
        Grey button: { class: 'AknButton--grey' }
        Grey light button: { class: 'AknButton--greyLight' }
        Slate grey button: { class: 'AknButton--slateGrey' }
        Important button: { class: 'AknButton--important' }
        Action button: { class: 'AknButton--action' }
        Disabled button: { class: 'AknButton--disabled' }
        Dropdown button: { class: 'AknButton--action AknButton--dropdown' }
        Glued buttons: { template: 'glued' }
        Square icon: { class: 'AknButton-squareIcon AknButton-squareIcon--id', text: '' }
    AknButtonList:
      description: "Prints a list of buttons. This can be used with a single button. By default, buttons are left-aligned."
      modifiers:
        Align right: { class: 'AknButtonList--right' }
        Align center: { class: 'AknButtonList--centered' }
        In two columns: { class: 'AknButtonList--twoColumns' }
    AknActionButton:
      description: "The action buttons are used for all the secondary actions on a page (it should not change or reload the current page)."
      modifiers:
        Action Button with caret: { template: 'withCaret' }
        Big action button: { class: 'AknActionButton--big' }
        Without border: { class: 'AknActionButton--withoutBorder' }
        With highlight: { template: 'withHighlight' }
        Disabled: { class: 'AknActionButton--disabled' }
        Unclickable action button: { class: 'AknActionButton--unclickable' }
    AknSeveralActionsButton:
      description: "Prints a button with several actions: a primary action and secondary actions. The text of the primary action is displayed on the button, and a caret is available to display the other actions."
      modifiers:
        Apply button: { class: 'AknSeveralActionsButton--apply' }
        Action button: { class: 'AknSeveralActionsButton--action' }
        Small button: { class: 'AknSeveralActionsButton--small' }
    AknDropdownButton:
      description: "Prints a button to choose the action within a dropdown (there is no primary action)."
      modifiers:
        Apply button: { class: 'AknDropdownButton--apply', caretClass: 'AknCaret--apply' }
        Important button: { class: 'AknDropdownButton--important', caretClass: 'AknCaret--important' }
        Small button: { class: 'AknDropdownButton--small' }
    AknIconButton:
      description: "Prints a single button with a unique icon."
      dark: true
      modifiers:
        Light icon button: { class: 'AknIconButton--light', dark: true }
        Dark icon button: { class: 'AknIconButton--dark', dark: true }
        Grey icon button: { class: 'AknIconButton--grey', dark: true }
        Important icon button: { class: 'AknIconButton--important', dark: true }
        Apply icon button: { class: 'AknIconButton--apply', dark: true }
        Small icon button: { class: 'AknIconButton--small', dark: true }
    AknSelectButton:
      description: "Displays a checkbox"
      dark: true
      modifiers:
        Selected: { class: 'AknSelectButton--selected' }
        Partial: { class: 'AknSelectButton--partial' }
        Disabled: { class: 'AknSelectButton--disabled' }

  Filters:
    AknFilterBox:
      description: "The filter box contains a set of filters."
      modifiers:
        With search: { template: 'search' }
    AknFilterChoice:
      description: "Prints a complete filter with an action and a field."

  Grids:
    AknGrid:
      modifiers:
        With full line: { template: 'withFullLine' }
        With custom cells: { template: 'withCustomCells' }
        With align: { template: 'withAlign' }
        With carets: { template: 'withCarets' }
        Condensed: { class: 'AknGrid--condensed' }
        Unclickable: { class: 'AknGrid--unclickable' }
    AknGridContainer:
      description: "This is a container for a grid. The goal is to display the empty set."
    AknGridToolbar: ~

  Forms:
    AknFormContainer:
      description: "Prints a fixed-width container for listing form elements vertically."
      modifiers:
        With padding: { class: 'AknFormContainer--withPadding' }
        Centered: { class: 'AknFormContainer--centered' }
        Expanded: { class: 'AknFormContainer--expanded' }
    AknFieldContainer:
      description: "A Field container is mainly composed of a label and an input. You can create a very simple field container with these 2 elements. You can also add a footer (for validation errors, for example), add icons next to the input, etc. Basically, a field container will take all the width of the parent container. To resize it, use the AknFormContainer module."
      modifiers:
        Complete: { template: 'complete' }
    AknTextField:
      description: "Prints a simple text field. The radius modifiers can be used to create inline forms."
      modifiers:
        Without right radius: { class: 'AknTextField--noRightRadius' }
        Without left radius: { class: 'AknTextField--noLeftRadius' }
        Without radius: { class: 'AknTextField--noRadius' }
        With right button: { template: 'withRightButton' }
        Disabled: { class: 'AknTextField--disabled' }
    AknTextareaField:
      modifiers:
        Small: { class: 'AknTextareaField--small' }
        Disabled: { attribute: 'disabled' }
    AknMetricField:
      description: "Prints an inline field containing a text field and a dropdown menu to choose a unit."
    AknPriceList:
      description: "Prints a list of prices. The width of each price is computed to display 3 inline prices on an AknFormContainer"
    AknMediaField: ~
    AknComparableFields:
      description: "Displays 2 FieldContainer side by side, with a checkbox in between."
    AknState: ~

  Navigation:
    AknSubsection: ~
    AknHorizontalNavtab: ~
    AknVerticalNavtab:
      modifiers:
        Condensed: { class: 'AknVerticalNavtab--condensed' }
    AknBreadcrumb:
      modifiers:
        Final: { template: 'final', class: 'AknBreadcrumb-item--final' }
        Routable: { template: 'final', class: 'AknBreadcrumb-item--routable' }
    AknSteps: ~
    AknVariantNavigation: ~

  Templates:
    AknColumnConfigurator: ~
    AknFooter:
      description: "Prints a discreet list of information."
    AknHeader: ~
    AknNotification:
      modifiers:
        Unread: { linkClass: 'AknNotification-link--new' }
        Icon List: { template: 'iconList' }
    AknNotificationList: ~
    AknProjectWidget: ~
    AknSequentialEdit: ~
    AknTitleContainer:
      modifiers:
        Complete: { template: 'complete' }
    AknWidget:
      modifiers:
        withPadding: { contentClass: 'AknWidget-content--withPadding' }
    AknInfoBlock:
      description: "Prints a centered text for additional information."
    AknCommentPanel: ~

  Other:
    AknBadge:
      modifiers:
        Big: { class: 'AknBadge--big' }
        Large: { class: 'AknBadge--large' }
        Small: { class: 'AknBadge--small', text: '' }
        With icon: { template: 'withIcon' }
        Success: { class: 'AknBadge--success' }
        Important: { class: 'AknBadge--important' }
        Warning: { class: 'AknBadge--warning' }
        Grey: { class: 'AknBadge--grey' }
        Highlight: { class: 'AknBadge--highlight' }
        Light: { class: 'AknBadge--light' }
    AknFlash:
      modifiers:
        Success: { class: 'AknFlash--success', closeIcon: 'icon-delete-greendark.svg', icon: 'icon-check.svg' }
        Warning: { class: 'AknFlash--warning', closeIcon: 'icon-delete-orangedark.svg', icon: 'icon-warning-orangelight.svg' }
        Danger: { class: 'AknFlash--error', closeIcon: 'icon-delete-reddark.svg', icon: 'icon-warning-redlight.svg' }
    AknLoadingMask:
      description: "The loading mask is used when an element is being loaded. Please note than all the style attributes in the source example are automatically generated by the application, you don't need to add them."
    AknMessageBox:
      modifiers:
        Apply: { class: 'AknMessageBox--apply' }
        Warning: { class: 'AknMessageBox--warning' }
        Danger: { class: 'AknMessageBox--danger' }
        Centered: { class: 'AknMessageBox--centered' }
    AknProgress:
      modifiers:
        Apply: { class: 'AknProgress--apply' }
        Warning: { class: 'AknProgress--warning' }
        Small: { class: 'AknProgress--small' }
        Micro: { class: 'AknProgress--micro' }
        Main: { class: 'AknProgress--main' }
    AknVerticalList:
      modifiers:
        Without border: { class: 'AknVerticalList--withoutBorder' }
        Selectable items: { itemClass: 'selectableItems' }
        Movable items: { template: 'movableItems' }
    AknAcl:
      modifiers:
        Granted: { iconClass: 'AknAcl-icon--granted', icon: 'icon-ok' }
        Non granted: { iconClass: 'AknAcl-icon--nonGranted', icon: 'icon-remove' }
        Centered: { class: 'AknAcl--centered' }
    AknDiff:
      description: "Displays text with differences (add or remove). Basically, the style only displays inline text, so you have to use one of the available modifiers to see the difference."
      modifiers:
        Remove: { class: 'AknDiff--remove' }
        Add: { class: 'AknDiff--add' }
    AknList:
      modifiers:
        With discs: { class: 'AknList--withDisc' }
    AknSquareList: ~
