parameters:
    pim_catalog.datagrid.manager.product.class: Pim\Bundle\IcecatDemoBundle\Datagrid\ProductDatagridManager
    pim_catalog.datagrid.manager.association_product_datagrid.class: Pim\Bundle\IcecatDemoBundle\Datagrid\AssociationProductDatagridManager
    pim_icecatdemo.datagrid.manager.vendor.class: Pim\Bundle\IcecatDemoBundle\Datagrid\VendorDatagridManager

services:
    pim_icecatdemo.datagrid.manager.vendor:
            class: "%pim_icecatdemo.datagrid.manager.vendor.class%"
            tags:
                - name:               oro_grid.datagrid.manager
                  datagrid_name:      vendors
                  entity_hint:        vendors
                  route_name:         pim_customentity_index
                  custom_entity_name: vendor
