parameters:
    pim_datagrid.product.attribute_type.acme_color:
        column:
            type:        flexible_option
            selector:    flexible_option
        filter:
            type:        flexible_choice
            parent_type: ajax_choice
            options:
                field_options:
                    multiple: true
        sorter:          flexible_field

services:
    acme_catalog.attributetype.color:
        class: %pim_custom_entity.attribute_type.custom_option_simple_select.class%
        arguments:
            - color
            - pim_ajax_entity
            - '@pim_catalog.validator.attribute_constraint_guesser'
            - acme_catalog_color
            - Acme\Bundle\CatalogBundle\Entity\Color
        tags:
            - { name: pim_catalog.attribute_type, alias: acme_catalog_color, entity: %pim_catalog.entity.product.class% }

