connector:
    name: Specific Connector
    jobs:
        specific_product_import:
            title: acme_specific_connector.jobs.specific_product_import.title
            type:  import
            steps:
                import:
                   title: acme_specific_connector.jobs.specific_product_import.import.title
                   services:
                       reader:    acme_specific_connector.reader.file.xml_product
                       processor: acme_specific_connector.processor.product
                       writer:    acme_specific_connector.writer.orm_product

